markdown: rdiscount
pygments: true # is true regardles on github pages
permalink: /:year/:month/:title
safe: false
exclude: 
    - README.md
    - index.html
    - CNAME
    - Rakefile
    - Guardfile
    - Gemfile
    - Gemfile.lock
baseurl: ''
excerpt_separator: "<!--break-->"
host: localhost
